name: Dockerized Flask CI/CD

on:
  push:
    branches: [ main ]

jobs:
  dockerized-ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTIONS: true

    services:
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --name test-redis

    steps:
    - name: Reposu klonla
      uses: actions/checkout@v3

    - name: Docker imajını oluştur
      run: docker build -t large-app .

    - name: Docker container’ı başlat (test)
      run: docker run -d --network=host -p 5050:5000 --name test-container large-app

    - name: Bekleyip uygulamayı test et
      run: |
        sleep 15
        curl --fail http://localhost:5050/health || (echo "Uygulama çalışmıyor!" && exit 1)

    - name: Temizle
      run: docker stop test-container && docker rm test-container
